### ISSUE TITLE
Cryptocurrency prices 

### ISSUE THREAD

**Issue by neuralgia** [pastudan/altfolio-live#6] opened 2018-06-05 18:12 UTC
Would be awesome if it could do cryptocurrency prices out to more than 2 decimals instead of rounding up to $.01 or just showing at $.00. Thanks.

**Comment by pastudan** [comment] 2018-06-07 00:39
This might be caused by the fact that I have to use a hack with the scrolling library I use in order to fix the decimal at 2 places. what’s the price you see vs the price you expect to see?

**Comment by neuralgia** [comment] 2018-06-08 03:14
Thanks for quick reply.  Some examples, LYL displays as $0.01, when actual value is $.006288. So its calculating it at $.01 which is way overestimating the value.  Some other examples, CV shows as $0.00, when should be $0.002488, which is causing it to show as estimate value of $0.  So really its only the cryptos that are under $.01/share that are most affected it seems.

**Comment by pastudan** [comment] 2018-06-09 16:19
Oof.. yeah, that's a pretty big bug! The fix should be simple, I just need to calculate using the actual value rather than the truncated display value. 

I'll try to get the fix out soon. Thanks for pointing it out.

**Comment by neuralgia** [comment] 2018-06-09 16:46
No worries.  I love your website, very handy.  I'm not sure what is happening, but sometimes I have to re-enter all my holdings.  I'm assuming it's some type of browser history clear that does it.  But if there was a way to manually save a "copy" of your holdings in a file and then reload that would be cool.  Probably a lot of work, but something to think about.

**Comment by pastudan** [comment] 2018-06-14 21:11
@neuralgia https://github.com/pastudan/altfolio-live/commit/ecad4569c062f83e934b6fe9fc5fe2ef50dd9da4 fixes the price calculation issue. The fix has been deployed so you should see it live on the site.

![image](https://user-images.githubusercontent.com/1296162/41438552-7381708c-6fdc-11e8-8b6c-5b893a58543a.png)

As for the holdings, clearing your browser history certainly does clear your holdings, since those are stored in [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). To avoid that issue, I'd need to build a login system and store all your holdings server-side, which I'm not ready to do. I left some thoughts on one way to achieve this in [this issue](https://github.com/pastudan/altfolio-live/issues/5). If someone builds that functionality, or similar, I'd be happy to merge it in.

**Closed as completed** 2018-06-14 21:11 UTC
